#!/bin/bash

Usage () { cat >&2 <<EOF
Usage: $0 <prefix> <port> <datadir> <logsdir> [...]
EOF
}

if [ $# -lt 4 ] ; then
  Usage
  exit 2
fi

prefix=$1 ; shift
port=$1 ; shift
datadir=$1 ; shift
logsdir=$1 ; shift

set -e

export PATH="$prefix/bin:$PATH"

common_opts=(
    --basedir="$prefix"
    --datadir="$datadir"
    --port="$port"
)
pidfile="$datadir/mysqld.pid"

start () {
  mysqld_safe \
      --no-defaults \
      "${common_opts[@]}" \
      --pid-file="$pidfile" \
      --log-error="$logsdir/mysqld-$(date -u '+%Y%m%d-%H%M%S').log" \
  </dev/null >/dev/null 2>/dev/null &
}

stop () {
  [ -r "$pidfile" ] && kill -TERM $(cat "$pidfile")
}

case "$1" in
  init)
    shift
    "$prefix/scripts/mysql_install_db" --no-defaults "${common_opts[@]}"
    sleep 1
    start
    sleep 2
    mysqladmin -u root password mysql
    stop
    ;;
  stop)
    shift
    stop
    ;;
  start)
    shift
    start
    ;;
esac
