#!/bin/bash

Usage () { cat >&2 <<EOF
Usage: $0 <tarfile> <prefix>
EOF
}

if [ $# -ne 2 ] ; then
  Usage
  exit 2
fi

tarfile=$1
prefix=$2

build_dir=$( mkbuilddir )

set -e
set -x

tar xf "$tarfile" -C "$build_dir"
cd "$build_dir/libffi-"*
./configure --prefix="$prefix"
make
make install
