#!/bin/bash

. "$( dirname "${BASH_SOURCE[0]}" )/functions" || exit $?

############################################################

prepare () {
  check_cmake
  check_hammerdb
}

############################################################

check_cmake () {
  checkexe cmake && return 0
  requires curl \
  && load_settings cmake \
  && download "$cmake_download_url" "$cmake_download_file" \
  && install_cmake "$DOWNLOADS/$cmake_download_file" "$HELPERS"
}

check_hammerdb () {
  checkexe "$HELPERS/hammerdb/hammerdb.tcl" && return 0
  requires curl \
  && load_settings hammerdb \
  && download "$hammerdb_download_url" "$hammerdb_download_file" \
  && install_hammerdb "$DOWNLOADS/$hammerdb_download_file" "$HELPERS/hammerdb"
}

############################################################

prepare
