#!/bin/bash
# :sw=2:ts=2:et:

export PYTHONUSERBASE="$HELPERS"
export PYTHONPATH="$HELPERS/lib/python$(python -c 'import sys; print(".".join(map(str,sys.version_info[:2])))')/site-packages"

############################################################

checkpipmodule () {
  pip show "$1" >/dev/null 2>/dev/null
}

pip_install () {
  pip install --isolated --user "$@"
}

############################################################
